name: sporran
version: 4.0.2
author: S. Hamblett <steve.hamblett@linux.com>
description: A PouchDB alike for Dart. Uses lawndart for local storage and Wilt for CouchDB access.
homepage: https://github.com/shamblett/sporran

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  wilt: 
    git: https://github.com/nmfisher/wilt
  json_object_lite: '^2.0.0'
  synchronized: 2.1.0+1

dev_dependencies:
  test: '^1.3.0'
  coverage: '^0.12.2'
  #dart_dev: '^2.0.0-alpha'
  dart_style: '^1.1.3'
  dartdoc: '^0.28.4'
  build_runner: '^1.6.5'
  build_test: '^0.10.8'
  build_web_compilers: '^2.1.4'
  stack_trace: 1.9.3